-- Seeds: pomodoro-service — 20+ sesiones por usuario (usuarios 1-5)

SET search_path TO pomodoro;

INSERT INTO pomodoro_sessions (user_id, session_type, status, duration_minutes, start_time, end_time, created_at) VALUES
  -- === USUARIO 1 (Felipe) — 28 sesiones ===
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'30 days 9 hours', NOW()-INTERVAL'30 days 8 hours 35 minutes', NOW()-INTERVAL'30 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'30 days 11 hours',NOW()-INTERVAL'30 days 10 hours 35 minutes',NOW()-INTERVAL'30 days'),
  ('1','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'29 days 9 hours', NOW()-INTERVAL'29 days 8 hours 20 minutes', NOW()-INTERVAL'29 days'),
  ('1','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'29 days 11 hours',NOW()-INTERVAL'29 days 10 hours 20 minutes',NOW()-INTERVAL'29 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'28 days 9 hours', NOW()-INTERVAL'28 days 8 hours 10 minutes', NOW()-INTERVAL'28 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'27 days 10 hours',NOW()-INTERVAL'27 days 9 hours 35 minutes', NOW()-INTERVAL'27 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'27 days 14 hours',NOW()-INTERVAL'27 days 13 hours 35 minutes',NOW()-INTERVAL'27 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'26 days 9 hours', NOW()-INTERVAL'26 days 8 hours 10 minutes', NOW()-INTERVAL'26 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'25 days 10 hours',NOW()-INTERVAL'25 days 9 hours 10 minutes', NOW()-INTERVAL'25 days'),
  ('1','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'24 days 9 hours', NOW()-INTERVAL'24 days 8 hours 20 minutes', NOW()-INTERVAL'24 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'23 days 8 hours', NOW()-INTERVAL'23 days 7 hours 35 minutes', NOW()-INTERVAL'23 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'23 days 10 hours',NOW()-INTERVAL'23 days 9 hours 35 minutes', NOW()-INTERVAL'23 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'22 days 9 hours', NOW()-INTERVAL'22 days 8 hours 35 minutes', NOW()-INTERVAL'22 days'),
  ('1','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'21 days 10 hours',NOW()-INTERVAL'21 days 9 hours 20 minutes', NOW()-INTERVAL'21 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'20 days 9 hours', NOW()-INTERVAL'20 days 8 hours 10 minutes', NOW()-INTERVAL'20 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'19 days 10 hours',NOW()-INTERVAL'19 days 9 hours 10 minutes', NOW()-INTERVAL'19 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'18 days 9 hours', NOW()-INTERVAL'18 days 8 hours 35 minutes', NOW()-INTERVAL'18 days'),
  ('1','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'17 days 10 hours',NOW()-INTERVAL'17 days 9 hours 20 minutes', NOW()-INTERVAL'17 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'16 days 9 hours', NOW()-INTERVAL'16 days 8 hours 35 minutes', NOW()-INTERVAL'16 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'15 days 9 hours', NOW()-INTERVAL'15 days 8 hours 10 minutes', NOW()-INTERVAL'15 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'10 days 9 hours', NOW()-INTERVAL'10 days 8 hours 35 minutes', NOW()-INTERVAL'10 days'),
  ('1','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'9 days 10 hours', NOW()-INTERVAL'9 days 9 hours 20 minutes',  NOW()-INTERVAL'9 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'8 days 9 hours',  NOW()-INTERVAL'8 days 8 hours 10 minutes',  NOW()-INTERVAL'8 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'7 days 9 hours',  NOW()-INTERVAL'7 days 8 hours 35 minutes',  NOW()-INTERVAL'7 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'5 days 10 hours', NOW()-INTERVAL'5 days 9 hours 35 minutes',  NOW()-INTERVAL'5 days'),
  ('1','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'3 days 9 hours',  NOW()-INTERVAL'3 days 8 hours 20 minutes',  NOW()-INTERVAL'3 days'),
  ('1','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'2 days 9 hours',  NOW()-INTERVAL'2 days 8 hours 10 minutes',  NOW()-INTERVAL'2 days'),
  ('1','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'1 day 9 hours',   NOW()-INTERVAL'1 day 8 hours 35 minutes',   NOW()-INTERVAL'1 day'),

  -- === USUARIO 2 (María) — 22 sesiones ===
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'28 days 10 hours',NOW()-INTERVAL'28 days 9 hours 35 minutes', NOW()-INTERVAL'28 days'),
  ('2','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'26 days 10 hours',NOW()-INTERVAL'26 days 9 hours 20 minutes', NOW()-INTERVAL'26 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'25 days 9 hours', NOW()-INTERVAL'25 days 8 hours 35 minutes', NOW()-INTERVAL'25 days'),
  ('2','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'24 days 10 hours',NOW()-INTERVAL'24 days 9 hours 10 minutes', NOW()-INTERVAL'24 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'22 days 9 hours', NOW()-INTERVAL'22 days 8 hours 35 minutes', NOW()-INTERVAL'22 days'),
  ('2','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'21 days 10 hours',NOW()-INTERVAL'21 days 9 hours 20 minutes', NOW()-INTERVAL'21 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'20 days 9 hours', NOW()-INTERVAL'20 days 8 hours 35 minutes', NOW()-INTERVAL'20 days'),
  ('2','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'17 days 9 hours', NOW()-INTERVAL'17 days 8 hours 10 minutes', NOW()-INTERVAL'17 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'15 days 10 hours',NOW()-INTERVAL'15 days 9 hours 35 minutes', NOW()-INTERVAL'15 days'),
  ('2','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'13 days 9 hours', NOW()-INTERVAL'13 days 8 hours 20 minutes', NOW()-INTERVAL'13 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'11 days 10 hours',NOW()-INTERVAL'11 days 9 hours 35 minutes', NOW()-INTERVAL'11 days'),
  ('2','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'9 days 9 hours',  NOW()-INTERVAL'9 days 8 hours 10 minutes',  NOW()-INTERVAL'9 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'7 days 10 hours', NOW()-INTERVAL'7 days 9 hours 35 minutes',  NOW()-INTERVAL'7 days'),
  ('2','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'5 days 9 hours',  NOW()-INTERVAL'5 days 8 hours 20 minutes',  NOW()-INTERVAL'5 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'4 days 10 hours', NOW()-INTERVAL'4 days 9 hours 35 minutes',  NOW()-INTERVAL'4 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'3 days 9 hours',  NOW()-INTERVAL'3 days 8 hours 35 minutes',  NOW()-INTERVAL'3 days'),
  ('2','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'2 days 10 hours', NOW()-INTERVAL'2 days 9 hours 10 minutes',  NOW()-INTERVAL'2 days'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'1 day 9 hours',   NOW()-INTERVAL'1 day 8 hours 35 minutes',   NOW()-INTERVAL'1 day'),
  ('2','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'8 hours',         NOW()-INTERVAL'7 hours 20 minutes',          NOW()-INTERVAL'8 hours'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'5 hours',         NOW()-INTERVAL'4 hours 35 minutes',          NOW()-INTERVAL'5 hours'),
  ('2','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'3 hours',         NOW()-INTERVAL'2 hours 35 minutes',          NOW()-INTERVAL'3 hours'),
  ('2','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'1 hour',          NOW()-INTERVAL'10 minutes',                  NOW()-INTERVAL'1 hour'),

  -- === USUARIO 3 (Carlos) — 20 sesiones ===
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'25 days 9 hours', NOW()-INTERVAL'25 days 8 hours 35 minutes', NOW()-INTERVAL'25 days'),
  ('3','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'24 days 10 hours',NOW()-INTERVAL'24 days 9 hours 20 minutes', NOW()-INTERVAL'24 days'),
  ('3','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'21 days 10 hours',NOW()-INTERVAL'21 days 9 hours 10 minutes', NOW()-INTERVAL'21 days'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'20 days 9 hours', NOW()-INTERVAL'20 days 8 hours 35 minutes', NOW()-INTERVAL'20 days'),
  ('3','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'17 days 9 hours', NOW()-INTERVAL'17 days 8 hours 20 minutes', NOW()-INTERVAL'17 days'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'15 days 10 hours',NOW()-INTERVAL'15 days 9 hours 35 minutes', NOW()-INTERVAL'15 days'),
  ('3','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'13 days 9 hours', NOW()-INTERVAL'13 days 8 hours 10 minutes', NOW()-INTERVAL'13 days'),
  ('3','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'11 days 10 hours',NOW()-INTERVAL'11 days 9 hours 20 minutes', NOW()-INTERVAL'11 days'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'9 days 9 hours',  NOW()-INTERVAL'9 days 8 hours 35 minutes',  NOW()-INTERVAL'9 days'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'7 days 10 hours', NOW()-INTERVAL'7 days 9 hours 35 minutes',  NOW()-INTERVAL'7 days'),
  ('3','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'6 days 9 hours',  NOW()-INTERVAL'6 days 8 hours 10 minutes',  NOW()-INTERVAL'6 days'),
  ('3','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'4 days 9 hours',  NOW()-INTERVAL'4 days 8 hours 20 minutes',  NOW()-INTERVAL'4 days'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'3 days 10 hours', NOW()-INTERVAL'3 days 9 hours 35 minutes',  NOW()-INTERVAL'3 days'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'2 days 9 hours',  NOW()-INTERVAL'2 days 8 hours 35 minutes',  NOW()-INTERVAL'2 days'),
  ('3','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'1 day 10 hours',  NOW()-INTERVAL'1 day 9 hours 10 minutes',   NOW()-INTERVAL'1 day'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'10 hours',        NOW()-INTERVAL'9 hours 35 minutes',          NOW()-INTERVAL'10 hours'),
  ('3','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'7 hours',         NOW()-INTERVAL'6 hours 20 minutes',          NOW()-INTERVAL'7 hours'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'5 hours',         NOW()-INTERVAL'4 hours 35 minutes',          NOW()-INTERVAL'5 hours'),
  ('3','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'3 hours',         NOW()-INTERVAL'2 hours 10 minutes',          NOW()-INTERVAL'3 hours'),
  ('3','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'1 hour',          NOW()-INTERVAL'35 minutes',                  NOW()-INTERVAL'1 hour'),

  -- === USUARIO 4 (Ana) — 20 sesiones ===
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'20 days 10 hours',NOW()-INTERVAL'20 days 9 hours 35 minutes', NOW()-INTERVAL'20 days'),
  ('4','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'19 days 9 hours', NOW()-INTERVAL'19 days 8 hours 20 minutes', NOW()-INTERVAL'19 days'),
  ('4','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'16 days 10 hours',NOW()-INTERVAL'16 days 9 hours 10 minutes', NOW()-INTERVAL'16 days'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'15 days 9 hours', NOW()-INTERVAL'15 days 8 hours 35 minutes', NOW()-INTERVAL'15 days'),
  ('4','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'14 days 10 hours',NOW()-INTERVAL'14 days 9 hours 20 minutes', NOW()-INTERVAL'14 days'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'13 days 9 hours', NOW()-INTERVAL'13 days 8 hours 35 minutes', NOW()-INTERVAL'13 days'),
  ('4','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'11 days 9 hours', NOW()-INTERVAL'11 days 8 hours 10 minutes', NOW()-INTERVAL'11 days'),
  ('4','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'9 days 9 hours',  NOW()-INTERVAL'9 days 8 hours 20 minutes',  NOW()-INTERVAL'9 days'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'7 days 10 hours', NOW()-INTERVAL'7 days 9 hours 35 minutes',  NOW()-INTERVAL'7 days'),
  ('4','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'6 days 9 hours',  NOW()-INTERVAL'6 days 8 hours 10 minutes',  NOW()-INTERVAL'6 days'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'5 days 10 hours', NOW()-INTERVAL'5 days 9 hours 35 minutes',  NOW()-INTERVAL'5 days'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'4 days 9 hours',  NOW()-INTERVAL'4 days 8 hours 35 minutes',  NOW()-INTERVAL'4 days'),
  ('4','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'3 days 10 hours', NOW()-INTERVAL'3 days 9 hours 20 minutes',  NOW()-INTERVAL'3 days'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'2 days 9 hours',  NOW()-INTERVAL'2 days 8 hours 35 minutes',  NOW()-INTERVAL'2 days'),
  ('4','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'1 day 10 hours',  NOW()-INTERVAL'1 day 9 hours 10 minutes',   NOW()-INTERVAL'1 day'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'9 hours',         NOW()-INTERVAL'8 hours 35 minutes',          NOW()-INTERVAL'9 hours'),
  ('4','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'6 hours',         NOW()-INTERVAL'5 hours 20 minutes',          NOW()-INTERVAL'6 hours'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'4 hours',         NOW()-INTERVAL'3 hours 35 minutes',          NOW()-INTERVAL'4 hours'),
  ('4','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'2 hours',         NOW()-INTERVAL'1 hour 10 minutes',           NOW()-INTERVAL'2 hours'),
  ('4','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'30 minutes',      NOW()-INTERVAL'5 minutes',                   NOW()-INTERVAL'30 minutes'),

  -- === USUARIO 5 (Diego) — 20 sesiones ===
  ('5','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'15 days 10 hours',NOW()-INTERVAL'15 days 9 hours 20 minutes', NOW()-INTERVAL'15 days'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'14 days 9 hours', NOW()-INTERVAL'14 days 8 hours 35 minutes', NOW()-INTERVAL'14 days'),
  ('5','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'12 days 9 hours', NOW()-INTERVAL'12 days 8 hours 10 minutes', NOW()-INTERVAL'12 days'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'11 days 10 hours',NOW()-INTERVAL'11 days 9 hours 35 minutes', NOW()-INTERVAL'11 days'),
  ('5','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'10 days 9 hours', NOW()-INTERVAL'10 days 8 hours 20 minutes', NOW()-INTERVAL'10 days'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'9 days 10 hours', NOW()-INTERVAL'9 days 9 hours 35 minutes',  NOW()-INTERVAL'9 days'),
  ('5','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'7 days 10 hours', NOW()-INTERVAL'7 days 9 hours 10 minutes',  NOW()-INTERVAL'7 days'),
  ('5','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'5 days 10 hours', NOW()-INTERVAL'5 days 9 hours 20 minutes',  NOW()-INTERVAL'5 days'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'4 days 9 hours',  NOW()-INTERVAL'4 days 8 hours 35 minutes',  NOW()-INTERVAL'4 days'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'3 days 10 hours', NOW()-INTERVAL'3 days 9 hours 35 minutes',  NOW()-INTERVAL'3 days'),
  ('5','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'2 days 9 hours',  NOW()-INTERVAL'2 days 8 hours 10 minutes',  NOW()-INTERVAL'2 days'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'1 day 10 hours',  NOW()-INTERVAL'1 day 9 hours 35 minutes',   NOW()-INTERVAL'1 day'),
  ('5','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'11 hours',        NOW()-INTERVAL'10 hours 20 minutes',         NOW()-INTERVAL'11 hours'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'8 hours',         NOW()-INTERVAL'7 hours 35 minutes',          NOW()-INTERVAL'8 hours'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'6 hours',         NOW()-INTERVAL'5 hours 35 minutes',          NOW()-INTERVAL'6 hours'),
  ('5','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'4 hours',         NOW()-INTERVAL'3 hours 10 minutes',          NOW()-INTERVAL'4 hours'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'3 hours',         NOW()-INTERVAL'2 hours 35 minutes',          NOW()-INTERVAL'3 hours'),
  ('5','INTERMEDIATE','COMPLETED',40,NOW()-INTERVAL'2 hours',         NOW()-INTERVAL'1 hour 20 minutes',           NOW()-INTERVAL'2 hours'),
  ('5','STANDARD',    'COMPLETED',25,NOW()-INTERVAL'1 hour',          NOW()-INTERVAL'35 minutes',                  NOW()-INTERVAL'1 hour'),
  ('5','INTENSE',     'COMPLETED',50,NOW()-INTERVAL'20 minutes',      NOW()-INTERVAL'0 minutes',                   NOW()-INTERVAL'20 minutes')
ON CONFLICT DO NOTHING;
