spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://127.0.0.1:5437/enfoca_metrics
    username: postgres
    password: postgres

  flyway:
    enabled: true
    out-of-order: true

app:
  jwt:
    secret: dGhpcy1pcy1hLXZlcnktc2VjdXJlLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50LW9ubHk=
  pomodoro-service:
    url: http://localhost:8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:8083
    status-page-url: http://localhost:8083/actuator/info
    health-check-url: http://localhost:8083/actuator/health
    home-page-url: http://localhost:8083/

logging:
  level:
    online.enfoca.metricsservice: DEBUG
